apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: cluster-c5xdq-jn7bq-worker-us-east-2b-custom
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-c5xdq-jn7bq
      machine.openshift.io/cluster-api-machineset: cluster-c5xdq-jn7bq-worker-us-east-2b-custom
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-c5xdq-jn7bq
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-c5xdq-jn7bq-worker-us-east-2b-custom
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          effect: NoSchedule
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          kind: AWSMachineProviderConfig
          instanceType: g5.2xlarge
          ami:
            id: ami-022fbb77a3226215f
          iamInstanceProfile:
            id: cluster-c5xdq-jn7bq-worker-profile
          credentialsSecret:
            name: aws-cloud-credentials
          userDataSecret:
            name: worker-user-data
          placement:
            region: us-east-2
            availabilityZone: us-east-2b
          subnet:
            filters:
              - name: tag:Name
                values:
                  - cluster-c5xdq-jn7bq-subnet-private-us-east-2b
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - cluster-c5xdq-jn7bq-node
            - filters:
                - name: tag:Name
                  values:
                    - cluster-c5xdq-jn7bq-lb
          blockDevices:
            - ebs:
                volumeSize: 100
                volumeType: gp2
                encrypted: true
          tags:
            - name: kubernetes.io/cluster/cluster-c5xdq-jn7bq
              value: owned
            - name: Stack
              value: ocp4-cluster-c5xdq
            - name: env_type
              value: ocp4-cluster
            - name: guid
              value: c5xdq
            - name: owner
              value: unknown
            - name: platform
              value: rhpds
            - name: uuid
              value: 0b2f98d9-2883-5894-a450-a1fd53a58720
