apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: cluster-c5xdq-jn7bq-worker-us-east-2b-test-machineset
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-c5xdq-jn7bq
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-c5xdq-jn7bq
      machine.openshift.io/cluster-api-machineset: test-machineset
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-c5xdq-jn7bq
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-c5xdq-jn7bq-worker-us-east-2b-test-machineset
    spec:
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          kind: AWSMachineProviderConfig
          instanceType: m5.xlarge
          ami:
            id: ami-022fbb77a3226215f
          iamInstanceProfile:
            id: cluster-c5xdq-jn7bq-worker-profile
          credentialsSecret:
            name: aws-cloud-credentials
          userDataSecret:
            name: worker-user-data
          placement:
            region: us-east-2
            availabilityZone: us-east-2b
          subnet:
            filters:
              - name: tag:Name
                values:
                  - cluster-c5xdq-jn7bq-subnet-private-us-east-2b
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - cluster-c5xdq-jn7bq-node
            - filters:
                - name: tag:Name
                  values:
                    - cluster-c5xdq-jn7bq-lb
          blockDevices:
            - ebs:
                volumeSize: 100
                volumeType: gp2
                encrypted: true
          tags:
            - name: kubernetes.io/cluster/cluster-c5xdq-jn7bq
              value: owned
